### ISSUE TITLE
Delegated [Manage membership] for support staff

### ISSUE THREAD

**Issue by mccahill** [DukeLearningInnovation/learn.duke#114] opened 2018-04-09 14:10 UTC
As a departmental/college IT/Instructional support person I need to set up courses for instructors in my college, define who is in the role of TA, course developer, and other ad-hoc roles, and select the tool suite the community will use. (This is common in Fuqua and Law)

**Comment by profmikegreene** [comment] 2018-04-17 01:07
Duplicate of #85

**Closed by profmikegreene** 2018-04-17 01:07 UTC
Labels: epic1, epic5, user story
