### ISSUE TITLE
[Manage membership] and define roles for ad-hoc additions to community

### ISSUE THREAD

**Issue by mccahill** [DukeLearningInnovation/learn.duke#113] opened 2018-04-09 14:06 UTC
As an instructor I need to be able to mange who is in the TA role for my course because SIS does not always include this information in the official course enrollment data feed and I want to give TAs special access/capabilities in some of the tools for the community.

**Comment by profmikegreene** [comment] 2018-04-18 16:24
Duplicate of #37

**Closed by profmikegreene** 2018-04-18 16:24 UTC
Labels: epic2, user story
